### ISSUE TITLE
Os Managers não possuem uma forma de armazenar que instâncias eles gerenciam

### ISSUE THREAD

**Issue by barrafas** [barrafas/Engenharia_Software#2]
No momento, não temos como criar os métodos get pois não ainda não foi implementada nenhuma estrutura que armazene as informações das instâncias que eles gerenciam. Seria interessante a implementação de algum dicionário, por exemplo, que aceite como chave o id de um objeto para que ele possa ser retornado.

**Comment by RodrigoPintucci** [comment]
Corrigido, adicionei um atributo de dicionário pra cada
