### ISSUE TITLE
Falta de métodos setter no diagrama de classes

### ISSUE THREAD

**Issue by GustavoSanches55** [barrafas/Engenharia_Software#3]
Em algumas classes, no diagrama de classes, parecem faltar o método setter de alguns atributos. Como, por exemplo, na <<interface>>: elements na qual existem os métodos getter das schedules, users, title etc, mas não existem os métodos que settam esses valores. Isso está correto?

**Comment by RodrigoPintucci** [comment]
Tem razão, ajustado aqui
