### ISSUE TITLE
Falta da funcionalidade de filtro no get_elements() da classe Schedule no Diagrama de classes

### ISSUE THREAD

**Issue by VanessaWille** [barrafas/Engenharia_Software#4]
O diagrama de classes atual não inclui funcionalidade de filtro no método get_elements() da classe Schedule. Importante adicioná-lo para que possa ocorrer filtragem por tipo de elemento em casos como na comparação de conflito de horário de eventos, que não faz sentido ser comparado com elementos do tipo tarefa ou lembrete.

**Comment by RodrigoPintucci** [comment]
Adicionado! Aproveitei para remover algumas funções getters desnecessárias.
